/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SwavePlayer {
    'audioTitle': string;
    'audioUrl': string;
    'captionUrl': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSwavePlayerElement extends Components.SwavePlayer, HTMLStencilElement {}
  var HTMLSwavePlayerElement: {
    prototype: HTMLSwavePlayerElement;
    new (): HTMLSwavePlayerElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'swave-player': HTMLSwavePlayerElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SwavePlayer {
    'audioTitle'?: string;
    'audioUrl'?: string;
    'captionUrl'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'swave-player': SwavePlayer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'swave-player': LocalJSX.SwavePlayer & JSXBase.HTMLAttributes<HTMLSwavePlayerElement>;
    }
  }
}


