/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SwavePlayer {
    'audioTitle': string;
    'audioUrl': string;
    'captionUrl': string;
  }
}

declare global {


  interface HTMLSwavePlayerElement extends Components.SwavePlayer, HTMLStencilElement {}
  var HTMLSwavePlayerElement: {
    prototype: HTMLSwavePlayerElement;
    new (): HTMLSwavePlayerElement;
  };
  interface HTMLElementTagNameMap {
    'swave-player': HTMLSwavePlayerElement;
  }
}

declare namespace LocalJSX {
  interface SwavePlayer {
    'audioTitle'?: string;
    'audioUrl'?: string;
    'captionUrl'?: string;
  }

  interface IntrinsicElements {
    'swave-player': SwavePlayer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'swave-player': LocalJSX.SwavePlayer & JSXBase.HTMLAttributes<HTMLSwavePlayerElement>;
    }
  }
}


